server:
  port: ${PORT:10372}
  shutdown: graceful

spring:
  application:
    name: eureka-server
  lifecycle:
    timeout-per-shutdown-phase: 10s

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:10372/eureka/

  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info