#server.port=8761
#
#spring.application.name=eureka-server
#
#server.shutdown=graceful
#spring.lifecycle.timeout-per-shutdown-phase=10s
#
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
server:
  port: ${PORT:10372}
  shutdown: graceful

spring:
  application:
    name: eureka-server
  lifecycle:
    timeout-per-shutdown-phase: 10s

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
